stages:
    - build
    - security
    - deploy

# for a simple node.js build, this step is (almost) meaningless
build_app:
    image: maven:3.6.3-openjdk-8
    stage: build
    script: 
        - mvn clean package
    artifacts:
        paths:
            - target/verademo.war

veracode_scan:
    image: veracode/api-wrapper-java:latest
    stage: security
    script:
        # the scan WILL fail, so just fire and forget
        - java -jar /opt/veracode/api-wrapper.jar -vid $VERACODE_API_ID -vkey $VERACODE_API_KEY
            -action UploadAndScan -appname "VulnImages-Verademo" -createprofile false
            -filepath target/verademo.war -version "Commit ${CI_COMMIT_SHA:0:8} - Job $CI_JOB_ID"
    allow_failure: true

veracode_sca_scan:
    image: maven:3.6.3-openjdk-8
    stage: security
    script:
        - curl -sSL https://download.sourceclear.com/ci.sh | sh
                    
dockerize:
    image: docker:stable
    stage: deploy
    variables:
        DOCKER_DRIVER: overlay2
        # docker 19.03 has TLS on by default, see https://about.gitlab.com/releases/2019/07/31/docker-in-docker-with-docker-19-dot-03/
        DOCKER_TLS_CERTDIR: ""  
        REPOSITORY_URL: $REPO_URL
    services:
        - docker:19.03.0-dind
    before_script:
        - apk add --update python3 py-pip
        - pip3 install awscli
    script:
        - $(aws ecr get-login --no-include-email --region us-east-2)
        - docker build -t verademo:$CI_PIPELINE_ID .
        - docker tag verademo:$CI_PIPELINE_ID $REPOSITORY_URL:verademo-latest
        - docker tag verademo:$CI_PIPELINE_ID $REPOSITORY_URL:verademo-$CI_PIPELINE_ID
        - docker push $REPOSITORY_URL:verademo-latest
        - docker push $REPOSITORY_URL:verademo-$CI_PIPELINE_ID
    after_script:
        - docker images